export default [
    {
        key:"Home",
        name:"系统首页",
        url:"/manager/home"
    },
    {
        key:"Banner",
        name:"Banner图",
        url:"/manager/banner"
    },
    {
        key:"About",
        name:"关于我们",
        url:"/manager/about"
    },
    {
        key:"Contact",
        name:"联系我们",
        url:"/manager/contact"
    },
]